version: 0.2
env:
  variables:
    REPOSITORY_URI: "058264261029.dkr.ecr.us-east-1.amazonaws.com/bhuang-devops/backend-api"
    IMAGE_TAG: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building the Docker image..."
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION= $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - docker build -t $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .  # 构建 Docker 镜像

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION  # 推送镜像到 ECR
      - echo "Writing image details to file..."
      - |
        cat <<EOF > imageDetail.json
        [
        {"imageURI": "${REPOSITORY_URI}:${CODEBUILD_RESOLVED_SOURCE_VERSION}", "name": "go-simplehttp"}
        ]
        EOF

artifacts:
  files:
    - imageDetail.json