version: 0.2
env:
  variables:
    REPOSITORY_URI: "058264261029.dkr.ecr.us-east-1.amazonaws.com/bhuang-devops/backend-api"
    IMAGE_TAG: "${CODEBUILD_RESOLVED_SOURCE_VERSION}"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building the Docker image..."
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION= $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .  # 构建 Docker 镜像

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG  # 推送镜像到 ECR
      - echo "Writing image details to file..."
#      - printf '[{"name": "go-simplehttp", "imageURI": "%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json  # 使用 printf 输出到文件

artifacts:
  files:
#    - imagedefinitions.json  # 将镜像信息文件保存为构建工件，供后续阶段使用
