name: GitHub Context Example

on:
  workflow_dispatch

env:
  GLOBAL_VAR: "This is a global variable"

jobs:
  show-github-context:
    runs-on: ubuntu-latest
    steps:
#     https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
      - name: "Show GitHub Context"
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"

  show-env-context:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "Job level variable"
    steps:
      - name: "env context"
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo "Global Variable: ${{ env.GLOBAL_VAR }}"
          echo "Job Variable: ${{ env.JOB_VAR }}"
          echo "Step Variable: ${{ env.STEP_VAR }}"

  show-steps-context:
    runs-on: ubuntu-latest
#    steps 上下文
#    steps 上下文用于在同一个 job 中获取先前步骤的输出。每个步骤需要设置 id 才能通过 steps.<step_id>.outputs.<output_name> 访问输出。
#    steps.example_step.outputs.message：访问 example_step 步骤的输出。
    steps:
      - name: Set output in step
        id: example_step
        run: echo "message=Hello from previous step" >> $GITHUB_OUTPUT

      - name: Use step output
        run: |
          echo "Message: ${{ steps.example_step.outputs.message }}"

  show-secret-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Show Secret Context"
        run: |
          echo "Secret: ${{ secrets.PAT }}"

