name: GitHub Context Example

on:
  workflow_dispatch

jobs:
  show-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: "Show GitHub Context"
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
