name: Default Shell and Directory Example

on: [push]

defaults:
  run:
    shell: bash         # 设置默认 shell 为 bash
    working-directory: ./  # 设置默认工作目录为 当前 目录

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in src
        run: ls  # 将在 ./ 目录下运行 ls

      - name: Print working directory
        run: pwd  # 将在 ./ 目录下运行 pwd，默认 shell 是 bash
